// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv3ow1iKba90WllgG2qzIzSghjARvOXHQ',
    appId: '1:586899717746:web:92133d5264648834b88ceb',
    messagingSenderId: '586899717746',
    projectId: 'inventory-95846',
    authDomain: 'inventory-95846.firebaseapp.com',
    storageBucket: 'inventory-95846.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAakOXWyZWkLzh6zsqYYd_kiK4IGAEgaM',
    appId: '1:586899717746:android:ed8865dc5251f4bab88ceb',
    messagingSenderId: '586899717746',
    projectId: 'inventory-95846',
    storageBucket: 'inventory-95846.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkv7gb-SP5-VscaWk8K6ND55HJdmGAIus',
    appId: '1:586899717746:ios:65abe5f6fe071e95b88ceb',
    messagingSenderId: '586899717746',
    projectId: 'inventory-95846',
    storageBucket: 'inventory-95846.appspot.com',
    iosClientId: '586899717746-p33pi8jadr4qccb2thdivjm7bn4h28bo.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkv7gb-SP5-VscaWk8K6ND55HJdmGAIus',
    appId: '1:586899717746:ios:fbe971d7f66a7b24b88ceb',
    messagingSenderId: '586899717746',
    projectId: 'inventory-95846',
    storageBucket: 'inventory-95846.appspot.com',
    iosClientId: '586899717746-n8maruddrjlberbnsl2um4ic4l4ns6ec.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventory.RunnerTests',
  );
}
